###################################################################

# Created by write_sdc on Wed Sep 16 17:29:47 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_wire_load_model -name 5K_hvratio_1_4 -library NangateOpenCellLibrary
set_max_transition 0.2 [current_design]
set_max_area 0
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports RST]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports LD]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[31]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[30]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[29]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[28]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[27]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[26]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[25]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[24]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[23]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[22]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[21]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[20]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[19]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[18]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[17]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[16]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[15]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[14]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[13]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[12]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[11]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[10]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[9]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[8]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[7]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[6]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[5]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[4]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[3]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[2]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[1]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[0]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[31]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[30]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[29]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[28]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[27]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[26]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[25]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[24]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[23]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[22]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[21]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[20]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[19]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[18]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[17]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[16]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[15]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[14]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[13]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[12]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[11]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[10]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[9]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[8]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[7]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[6]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[5]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[4]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[3]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[2]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[1]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[0]}]
set_load -pin_load 0.05 [get_ports {P[63]}]
set_load -pin_load 0.05 [get_ports {P[62]}]
set_load -pin_load 0.05 [get_ports {P[61]}]
set_load -pin_load 0.05 [get_ports {P[60]}]
set_load -pin_load 0.05 [get_ports {P[59]}]
set_load -pin_load 0.05 [get_ports {P[58]}]
set_load -pin_load 0.05 [get_ports {P[57]}]
set_load -pin_load 0.05 [get_ports {P[56]}]
set_load -pin_load 0.05 [get_ports {P[55]}]
set_load -pin_load 0.05 [get_ports {P[54]}]
set_load -pin_load 0.05 [get_ports {P[53]}]
set_load -pin_load 0.05 [get_ports {P[52]}]
set_load -pin_load 0.05 [get_ports {P[51]}]
set_load -pin_load 0.05 [get_ports {P[50]}]
set_load -pin_load 0.05 [get_ports {P[49]}]
set_load -pin_load 0.05 [get_ports {P[48]}]
set_load -pin_load 0.05 [get_ports {P[47]}]
set_load -pin_load 0.05 [get_ports {P[46]}]
set_load -pin_load 0.05 [get_ports {P[45]}]
set_load -pin_load 0.05 [get_ports {P[44]}]
set_load -pin_load 0.05 [get_ports {P[43]}]
set_load -pin_load 0.05 [get_ports {P[42]}]
set_load -pin_load 0.05 [get_ports {P[41]}]
set_load -pin_load 0.05 [get_ports {P[40]}]
set_load -pin_load 0.05 [get_ports {P[39]}]
set_load -pin_load 0.05 [get_ports {P[38]}]
set_load -pin_load 0.05 [get_ports {P[37]}]
set_load -pin_load 0.05 [get_ports {P[36]}]
set_load -pin_load 0.05 [get_ports {P[35]}]
set_load -pin_load 0.05 [get_ports {P[34]}]
set_load -pin_load 0.05 [get_ports {P[33]}]
set_load -pin_load 0.05 [get_ports {P[32]}]
set_load -pin_load 0.05 [get_ports {P[31]}]
set_load -pin_load 0.05 [get_ports {P[30]}]
set_load -pin_load 0.05 [get_ports {P[29]}]
set_load -pin_load 0.05 [get_ports {P[28]}]
set_load -pin_load 0.05 [get_ports {P[27]}]
set_load -pin_load 0.05 [get_ports {P[26]}]
set_load -pin_load 0.05 [get_ports {P[25]}]
set_load -pin_load 0.05 [get_ports {P[24]}]
set_load -pin_load 0.05 [get_ports {P[23]}]
set_load -pin_load 0.05 [get_ports {P[22]}]
set_load -pin_load 0.05 [get_ports {P[21]}]
set_load -pin_load 0.05 [get_ports {P[20]}]
set_load -pin_load 0.05 [get_ports {P[19]}]
set_load -pin_load 0.05 [get_ports {P[18]}]
set_load -pin_load 0.05 [get_ports {P[17]}]
set_load -pin_load 0.05 [get_ports {P[16]}]
set_load -pin_load 0.05 [get_ports {P[15]}]
set_load -pin_load 0.05 [get_ports {P[14]}]
set_load -pin_load 0.05 [get_ports {P[13]}]
set_load -pin_load 0.05 [get_ports {P[12]}]
set_load -pin_load 0.05 [get_ports {P[11]}]
set_load -pin_load 0.05 [get_ports {P[10]}]
set_load -pin_load 0.05 [get_ports {P[9]}]
set_load -pin_load 0.05 [get_ports {P[8]}]
set_load -pin_load 0.05 [get_ports {P[7]}]
set_load -pin_load 0.05 [get_ports {P[6]}]
set_load -pin_load 0.05 [get_ports {P[5]}]
set_load -pin_load 0.05 [get_ports {P[4]}]
set_load -pin_load 0.05 [get_ports {P[3]}]
set_load -pin_load 0.05 [get_ports {P[2]}]
set_load -pin_load 0.05 [get_ports {P[1]}]
set_load -pin_load 0.05 [get_ports {P[0]}]
set_ideal_network [get_ports CLK]
set_ideal_network [get_ports RST]
create_clock [get_ports CLK]  -period 4  -waveform {0 2}
set_clock_latency 0.05  [get_clocks CLK]
set_clock_uncertainty 0.05  [get_clocks CLK]
set_clock_transition -max -rise 0.05 [get_clocks CLK]
set_clock_transition -max -fall 0.05 [get_clocks CLK]
set_clock_transition -min -rise 0.05 [get_clocks CLK]
set_clock_transition -min -fall 0.05 [get_clocks CLK]
set_input_delay -clock CLK  0.25  [get_ports RST]
set_input_delay -clock CLK  0.25  [get_ports LD]
set_input_delay -clock CLK  0.25  [get_ports {A[31]}]
set_input_delay -clock CLK  0.25  [get_ports {A[30]}]
set_input_delay -clock CLK  0.25  [get_ports {A[29]}]
set_input_delay -clock CLK  0.25  [get_ports {A[28]}]
set_input_delay -clock CLK  0.25  [get_ports {A[27]}]
set_input_delay -clock CLK  0.25  [get_ports {A[26]}]
set_input_delay -clock CLK  0.25  [get_ports {A[25]}]
set_input_delay -clock CLK  0.25  [get_ports {A[24]}]
set_input_delay -clock CLK  0.25  [get_ports {A[23]}]
set_input_delay -clock CLK  0.25  [get_ports {A[22]}]
set_input_delay -clock CLK  0.25  [get_ports {A[21]}]
set_input_delay -clock CLK  0.25  [get_ports {A[20]}]
set_input_delay -clock CLK  0.25  [get_ports {A[19]}]
set_input_delay -clock CLK  0.25  [get_ports {A[18]}]
set_input_delay -clock CLK  0.25  [get_ports {A[17]}]
set_input_delay -clock CLK  0.25  [get_ports {A[16]}]
set_input_delay -clock CLK  0.25  [get_ports {A[15]}]
set_input_delay -clock CLK  0.25  [get_ports {A[14]}]
set_input_delay -clock CLK  0.25  [get_ports {A[13]}]
set_input_delay -clock CLK  0.25  [get_ports {A[12]}]
set_input_delay -clock CLK  0.25  [get_ports {A[11]}]
set_input_delay -clock CLK  0.25  [get_ports {A[10]}]
set_input_delay -clock CLK  0.25  [get_ports {A[9]}]
set_input_delay -clock CLK  0.25  [get_ports {A[8]}]
set_input_delay -clock CLK  0.25  [get_ports {A[7]}]
set_input_delay -clock CLK  0.25  [get_ports {A[6]}]
set_input_delay -clock CLK  0.25  [get_ports {A[5]}]
set_input_delay -clock CLK  0.25  [get_ports {A[4]}]
set_input_delay -clock CLK  0.25  [get_ports {A[3]}]
set_input_delay -clock CLK  0.25  [get_ports {A[2]}]
set_input_delay -clock CLK  0.25  [get_ports {A[1]}]
set_input_delay -clock CLK  0.25  [get_ports {A[0]}]
set_input_delay -clock CLK  0.25  [get_ports {B[31]}]
set_input_delay -clock CLK  0.25  [get_ports {B[30]}]
set_input_delay -clock CLK  0.25  [get_ports {B[29]}]
set_input_delay -clock CLK  0.25  [get_ports {B[28]}]
set_input_delay -clock CLK  0.25  [get_ports {B[27]}]
set_input_delay -clock CLK  0.25  [get_ports {B[26]}]
set_input_delay -clock CLK  0.25  [get_ports {B[25]}]
set_input_delay -clock CLK  0.25  [get_ports {B[24]}]
set_input_delay -clock CLK  0.25  [get_ports {B[23]}]
set_input_delay -clock CLK  0.25  [get_ports {B[22]}]
set_input_delay -clock CLK  0.25  [get_ports {B[21]}]
set_input_delay -clock CLK  0.25  [get_ports {B[20]}]
set_input_delay -clock CLK  0.25  [get_ports {B[19]}]
set_input_delay -clock CLK  0.25  [get_ports {B[18]}]
set_input_delay -clock CLK  0.25  [get_ports {B[17]}]
set_input_delay -clock CLK  0.25  [get_ports {B[16]}]
set_input_delay -clock CLK  0.25  [get_ports {B[15]}]
set_input_delay -clock CLK  0.25  [get_ports {B[14]}]
set_input_delay -clock CLK  0.25  [get_ports {B[13]}]
set_input_delay -clock CLK  0.25  [get_ports {B[12]}]
set_input_delay -clock CLK  0.25  [get_ports {B[11]}]
set_input_delay -clock CLK  0.25  [get_ports {B[10]}]
set_input_delay -clock CLK  0.25  [get_ports {B[9]}]
set_input_delay -clock CLK  0.25  [get_ports {B[8]}]
set_input_delay -clock CLK  0.25  [get_ports {B[7]}]
set_input_delay -clock CLK  0.25  [get_ports {B[6]}]
set_input_delay -clock CLK  0.25  [get_ports {B[5]}]
set_input_delay -clock CLK  0.25  [get_ports {B[4]}]
set_input_delay -clock CLK  0.25  [get_ports {B[3]}]
set_input_delay -clock CLK  0.25  [get_ports {B[2]}]
set_input_delay -clock CLK  0.25  [get_ports {B[1]}]
set_input_delay -clock CLK  0.25  [get_ports {B[0]}]
set_output_delay -clock CLK  0.15  [get_ports {P[63]}]
set_output_delay -clock CLK  0.15  [get_ports {P[62]}]
set_output_delay -clock CLK  0.15  [get_ports {P[61]}]
set_output_delay -clock CLK  0.15  [get_ports {P[60]}]
set_output_delay -clock CLK  0.15  [get_ports {P[59]}]
set_output_delay -clock CLK  0.15  [get_ports {P[58]}]
set_output_delay -clock CLK  0.15  [get_ports {P[57]}]
set_output_delay -clock CLK  0.15  [get_ports {P[56]}]
set_output_delay -clock CLK  0.15  [get_ports {P[55]}]
set_output_delay -clock CLK  0.15  [get_ports {P[54]}]
set_output_delay -clock CLK  0.15  [get_ports {P[53]}]
set_output_delay -clock CLK  0.15  [get_ports {P[52]}]
set_output_delay -clock CLK  0.15  [get_ports {P[51]}]
set_output_delay -clock CLK  0.15  [get_ports {P[50]}]
set_output_delay -clock CLK  0.15  [get_ports {P[49]}]
set_output_delay -clock CLK  0.15  [get_ports {P[48]}]
set_output_delay -clock CLK  0.15  [get_ports {P[47]}]
set_output_delay -clock CLK  0.15  [get_ports {P[46]}]
set_output_delay -clock CLK  0.15  [get_ports {P[45]}]
set_output_delay -clock CLK  0.15  [get_ports {P[44]}]
set_output_delay -clock CLK  0.15  [get_ports {P[43]}]
set_output_delay -clock CLK  0.15  [get_ports {P[42]}]
set_output_delay -clock CLK  0.15  [get_ports {P[41]}]
set_output_delay -clock CLK  0.15  [get_ports {P[40]}]
set_output_delay -clock CLK  0.15  [get_ports {P[39]}]
set_output_delay -clock CLK  0.15  [get_ports {P[38]}]
set_output_delay -clock CLK  0.15  [get_ports {P[37]}]
set_output_delay -clock CLK  0.15  [get_ports {P[36]}]
set_output_delay -clock CLK  0.15  [get_ports {P[35]}]
set_output_delay -clock CLK  0.15  [get_ports {P[34]}]
set_output_delay -clock CLK  0.15  [get_ports {P[33]}]
set_output_delay -clock CLK  0.15  [get_ports {P[32]}]
set_output_delay -clock CLK  0.15  [get_ports {P[31]}]
set_output_delay -clock CLK  0.15  [get_ports {P[30]}]
set_output_delay -clock CLK  0.15  [get_ports {P[29]}]
set_output_delay -clock CLK  0.15  [get_ports {P[28]}]
set_output_delay -clock CLK  0.15  [get_ports {P[27]}]
set_output_delay -clock CLK  0.15  [get_ports {P[26]}]
set_output_delay -clock CLK  0.15  [get_ports {P[25]}]
set_output_delay -clock CLK  0.15  [get_ports {P[24]}]
set_output_delay -clock CLK  0.15  [get_ports {P[23]}]
set_output_delay -clock CLK  0.15  [get_ports {P[22]}]
set_output_delay -clock CLK  0.15  [get_ports {P[21]}]
set_output_delay -clock CLK  0.15  [get_ports {P[20]}]
set_output_delay -clock CLK  0.15  [get_ports {P[19]}]
set_output_delay -clock CLK  0.15  [get_ports {P[18]}]
set_output_delay -clock CLK  0.15  [get_ports {P[17]}]
set_output_delay -clock CLK  0.15  [get_ports {P[16]}]
set_output_delay -clock CLK  0.15  [get_ports {P[15]}]
set_output_delay -clock CLK  0.15  [get_ports {P[14]}]
set_output_delay -clock CLK  0.15  [get_ports {P[13]}]
set_output_delay -clock CLK  0.15  [get_ports {P[12]}]
set_output_delay -clock CLK  0.15  [get_ports {P[11]}]
set_output_delay -clock CLK  0.15  [get_ports {P[10]}]
set_output_delay -clock CLK  0.15  [get_ports {P[9]}]
set_output_delay -clock CLK  0.15  [get_ports {P[8]}]
set_output_delay -clock CLK  0.15  [get_ports {P[7]}]
set_output_delay -clock CLK  0.15  [get_ports {P[6]}]
set_output_delay -clock CLK  0.15  [get_ports {P[5]}]
set_output_delay -clock CLK  0.15  [get_ports {P[4]}]
set_output_delay -clock CLK  0.15  [get_ports {P[3]}]
set_output_delay -clock CLK  0.15  [get_ports {P[2]}]
set_output_delay -clock CLK  0.15  [get_ports {P[1]}]
set_output_delay -clock CLK  0.15  [get_ports {P[0]}]
