###################################################################

# Created by write_sdc on Thu Aug 27 03:33:29 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_wire_load_model -name 5K_hvratio_1_4 -library NangateOpenCellLibrary
set_max_transition 0.2 [current_design]
set_max_area 0
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports LD]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports RST]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[7]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[6]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[5]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[4]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[3]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[2]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[1]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {A[0]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[7]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[6]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[5]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[4]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[3]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[2]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[1]}]
set_driving_cell -lib_cell BUF_X4 -pin Z [get_ports {B[0]}]
set_load -pin_load 0.05 [get_ports {P[15]}]
set_load -pin_load 0.05 [get_ports {P[14]}]
set_load -pin_load 0.05 [get_ports {P[13]}]
set_load -pin_load 0.05 [get_ports {P[12]}]
set_load -pin_load 0.05 [get_ports {P[11]}]
set_load -pin_load 0.05 [get_ports {P[10]}]
set_load -pin_load 0.05 [get_ports {P[9]}]
set_load -pin_load 0.05 [get_ports {P[8]}]
set_load -pin_load 0.05 [get_ports {P[7]}]
set_load -pin_load 0.05 [get_ports {P[6]}]
set_load -pin_load 0.05 [get_ports {P[5]}]
set_load -pin_load 0.05 [get_ports {P[4]}]
set_load -pin_load 0.05 [get_ports {P[3]}]
set_load -pin_load 0.05 [get_ports {P[2]}]
set_load -pin_load 0.05 [get_ports {P[1]}]
set_load -pin_load 0.05 [get_ports {P[0]}]
set_ideal_network [get_ports CLK]
set_ideal_network [get_ports RST]
create_clock [get_ports CLK]  -period 3.5  -waveform {0 1.75}
set_clock_latency 0.05  [get_clocks CLK]
set_clock_uncertainty 0.05  [get_clocks CLK]
set_clock_transition -max -rise 0.05 [get_clocks CLK]
set_clock_transition -max -fall 0.05 [get_clocks CLK]
set_clock_transition -min -rise 0.05 [get_clocks CLK]
set_clock_transition -min -fall 0.05 [get_clocks CLK]
set_input_delay -clock CLK  0.25  [get_ports LD]
set_input_delay -clock CLK  0.25  [get_ports RST]
set_input_delay -clock CLK  0.25  [get_ports {A[7]}]
set_input_delay -clock CLK  0.25  [get_ports {A[6]}]
set_input_delay -clock CLK  0.25  [get_ports {A[5]}]
set_input_delay -clock CLK  0.25  [get_ports {A[4]}]
set_input_delay -clock CLK  0.25  [get_ports {A[3]}]
set_input_delay -clock CLK  0.25  [get_ports {A[2]}]
set_input_delay -clock CLK  0.25  [get_ports {A[1]}]
set_input_delay -clock CLK  0.25  [get_ports {A[0]}]
set_input_delay -clock CLK  0.25  [get_ports {B[7]}]
set_input_delay -clock CLK  0.25  [get_ports {B[6]}]
set_input_delay -clock CLK  0.25  [get_ports {B[5]}]
set_input_delay -clock CLK  0.25  [get_ports {B[4]}]
set_input_delay -clock CLK  0.25  [get_ports {B[3]}]
set_input_delay -clock CLK  0.25  [get_ports {B[2]}]
set_input_delay -clock CLK  0.25  [get_ports {B[1]}]
set_input_delay -clock CLK  0.25  [get_ports {B[0]}]
set_output_delay -clock CLK  0.15  [get_ports {P[15]}]
set_output_delay -clock CLK  0.15  [get_ports {P[14]}]
set_output_delay -clock CLK  0.15  [get_ports {P[13]}]
set_output_delay -clock CLK  0.15  [get_ports {P[12]}]
set_output_delay -clock CLK  0.15  [get_ports {P[11]}]
set_output_delay -clock CLK  0.15  [get_ports {P[10]}]
set_output_delay -clock CLK  0.15  [get_ports {P[9]}]
set_output_delay -clock CLK  0.15  [get_ports {P[8]}]
set_output_delay -clock CLK  0.15  [get_ports {P[7]}]
set_output_delay -clock CLK  0.15  [get_ports {P[6]}]
set_output_delay -clock CLK  0.15  [get_ports {P[5]}]
set_output_delay -clock CLK  0.15  [get_ports {P[4]}]
set_output_delay -clock CLK  0.15  [get_ports {P[3]}]
set_output_delay -clock CLK  0.15  [get_ports {P[2]}]
set_output_delay -clock CLK  0.15  [get_ports {P[1]}]
set_output_delay -clock CLK  0.15  [get_ports {P[0]}]
